// Generated by tools/generate-test-credentials
var test_credentials = {default_user: {username: 'iago@zulip.com', password: 'aXFkSNPEUDFy+BfO'}};
try { exports.test_credentials = test_credentials; } catch (e) {}
